name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*" # e.g v0.1.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read # allow checkout
      # id-token no longer required when using a classic API token
      # id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade build

      - name: Build sdist & wheel
        run: |
          python -m build --sdist --wheel --outdir dist/

      #  Classic token-based upload with Twine
      - name: Publish with Twine
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      # ──────────────────────────────────────────────────────
      #  If you later switch back to OIDC trusted publishing,
      #  comment the Twine step above and uncomment the block
      #  below, then remove the TWINE_API_TOKEN secret.
      # ──────────────────────────────────────────────────────
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.8.11
      #   with:
      #     verbose: true
      #     print-hash: true
