name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*" # e.g. v0.1.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read # allow checkout
      id-token: write # needed for OIDC trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade build

      - name: Build sdist & wheel
        run: |
          python -m build --sdist --wheel --outdir dist/

      # ---- Trusted publish via OIDC (no token needed) ----
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          verbose: true
          print-hash: true

      # ---- Classic token upload (uncomment if you prefer) ----
      # - name: Publish with Twine
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TWINE_API_TOKEN }}
      #   run: |
      #     python -m pip install --upgrade twine
      #     twine upload dist/*
